---
- name: FZF | Downloads FZF | git
  git:
    repo: "{{ fzf_url }}"
    dest: "{{ fzf_install_dir }}"
    depth: 1

- name: FZF | Install FZF | shell
  shell: "{{ fzf_install_dir }}/install --no-update-rc"
  args:
    creates: "{{ fzf_exe }}"
