---
- name: Get Rustup
  get_url:
    url: "{{ rustup_url }}"
    dest: "{{ rustup_script_path }}"
    mode: 0755

- name: Execute the Rustup Installer(Stable)
  changed_when: false
  shell: "{{ rustup_script_path }} -y --no-modify-path --default-toolchain {{ rustup_toolchain }}"

- name: Remove the Rustup Installer
  file:
    path: "{{ rustup_script_path }}"
    state: absent

- name: Rust | Install Rust MUSL Target | shell
  changed_when: false
  command: "{{ rustup_exe }} target add {{ rustup_musl_target }}"

- name: Install Cargo/Rust Dev Tools
  changed_when: false
  shell: "{{ rustc_env_variables }} {{ cargo_bin }} install --locked {{ item.value.name }}"
  args:
    creates: "{{ item.value.path }}"
  loop: "{{ cargo_packages | dict2items }}"

- name: Install Cargo/Rust Dev Tools
  shell: "{{ rustc_env_variables }} {{ cargo_binstall_exe }} {{ cargo_binstall_args }} --no-confirm {{ item.value.name }}"
  args:
    creates: "{{ item.value.path }}"
  loop: "{{ cargo_binstall_packages | dict2items }}"

- name: Install Cargo/Rust Tools for Rust Development
  shell: "{{ rustc_env_variables }} {{ cargo_binstall_exe }} {{ cargo_binstall_args }} --no-confirm {{ item.value.name }}"
  args:
    creates: "{{ item.value.path }}"
  loop: "{{ rust_dev_packages | dict2items }}"

- name: Rust | Install Tools for Rust Development | shell
  command: "{{ rustup_exe }} component add {{ item.value.name }}"
  args:
    creates: "{{ item.value.path }}"
  loop: "{{ rustup_dev_packages | dict2items }}"

- name: Rust | Update Installed Rust Packages | shell
  changed_when: false
  command: "{{ cargo_bin }} install-update -a"
