---
- name: Neovim | Setup Neovim Profile Directories | file
  file:
    path: "{{ item.value }}"
    state: directory
    mode: '0755'
  loop: "{{ nvim_xdg_profile_dir | dict2items }}"

- name: Neovim | Install Neovim Profile Configs | file
  vars:
    nvim_profile_name: "{{ profile_item.value.name }}"
    nvim_config_dir: "{{ nvim_xdg_profile_dir['config'] }}/{{ profile_item.value.name }}/nvim"
    nvim_share_dir: "{{ nvim_xdg_profile_dir['share'] }}/{{ profile_item.value.name }}/nvim"
    nvim_cache_dir: "{{ nvim_xdg_profile_dir['cache'] }}/{{ profile_item.value.name }}/nvim"
  include_tasks: tasks/install_neovim_profiles.yml
  loop: "{{ nvim_xdg_profiles | dict2items }}"
  loop_control:
    loop_var: profile_item

- name: Neovim | Copies Scripts | template
  vars:
    nvim_profile_name: "{{ profile_item.value.name }}"
    nvim_config_dir: "{{ nvim_xdg_profile_dir['config'] }}/{{ profile_item.value.name }}/nvim"
    nvim_share_dir: "{{ nvim_xdg_profile_dir['share'] }}/{{ profile_item.value.name }}/nvim"
    nvim_cache_dir: "{{ nvim_xdg_profile_dir['cache'] }}/{{ profile_item.value.name }}/nvim"
  template:
    src: "nvim/nvim-profile.j2"
    dest: "{{ bin_directory }}/nvim-{{ profile_item.value.name }}"
  loop: "{{ nvim_xdg_profiles | dict2items }}"
  loop_control:
    loop_var: profile_item

- name: Neovim | Copies Init Scripts | template
  vars:
    nvim_profile_name: "{{ profile_item.value.name }}"
    nvim_config_dir: "{{ nvim_xdg_profile_dir['config'] }}/{{ profile_item.value.name }}/nvim"
    nvim_share_dir: "{{ nvim_xdg_profile_dir['share'] }}/{{ profile_item.value.name }}/nvim"
    nvim_cache_dir: "{{ nvim_xdg_profile_dir['cache'] }}/{{ profile_item.value.name }}/nvim"
  template:
    src: "nvim/nvim-profile-init.j2"
    dest: "{{ bin_directory }}/nvim-init-{{ profile_item.value.name }}"
  loop: "{{ nvim_xdg_profiles | dict2items }}"
  loop_control:
    loop_var: profile_item

- name: Scripts | Change Script Permissions | file
  file:
    path: "{{ bin_directory }}"
    mode: +x
    state: directory
    recurse: yes
