---
- name: Neovim | Setup Neovim Profile Directories | file
  file:
    path: "{{ item.0.value }}/{{ item.1.value.appname }}"
    state: directory
    mode: '0755'
  loop: "{{ xdg_config_dirs | dict2items | product(nvim_xdg_profiles | dict2items) | list }}"

- name: Neovim | Setup Neovim Notes Directory | file
  file:
    path: "{{ nvim_neorg_dir }}"
    state: directory

- name: Neovim | Setup Neovim Profile Configs | template
  vars:
    nvim_xdg_profile_defaults: "{{ item.value['config']['defaults'] }}"
    nvim_xdg_profile_plugins: "{{ item.value['config']['plugins'] }}"
    nvim_xdg_profile_config: "{{ item.value['config']['config'] }}"
    nvim_xdg_profile_keybindings: "{{ item.value['config']['keymaps'] }}"
    nvim_xdg_profile_startup: "{{ item.value['config']['startup'] }}"
  template:
    src: nvim/init.lazy.lua.j2
    dest: "{{ xdg_config_dir }}/{{ item.value['appname'] }}/init.lua"
  loop: "{{ nvim_xdg_profiles | dict2items }}"
