---
- name: Zellij | Setup Zellij Plugin Directory | file
  file:
    path: "{{ zellij_plugin_dir }}"
    state: directory
    mode: '0755'

- name: Zellij | Download Zellij Plugins | get_url
  get_url:
    url: "{{ item.value.url }}"
    dest: "{{ zellij_plugin_dir }}"
    mode: 0755
  loop: "{{ zellij_plugins | dict2items }}"
