---
- name: Neovim | Setup Neovim Config Directory | file
  file:
    path: "{{ nvim_config_dir }}"
    state: directory
    mode: '0755'

- name: Neovim | Setup Neovim Share(Data) Directory | file
  file:
    path: "{{ nvim_share_dir }}"
    state: directory
    mode: '0755'

- name: Neovim | Setup Neovim Cache Directory | file
  file:
    path: "{{ nvim_cache_dir }}"
    state: directory
    mode: '0755'

- name: Neovim | Create Neovim Plugin Config Directories | file
  ansible.builtin.file:
    path: "{{ nvim_config_dir }}/{{ item.path }}"
    state: directory
  with_community.general.filetree: "../templates/nvim-{{ nvim_profile_name }}"
  when: item.state == 'directory'

- name: Neovim | Copy Neovim Plugin Config Files | template
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ nvim_config_dir }}/{{ item.path | regex_replace('\\.j2$', '') }}"
  with_community.general.filetree: "../templates/nvim-{{ nvim_profile_name }}"
  when: item.state == 'file'

- name: Neovim | Download Packer | git
  git:
    repo: "{{ packer_url }}"
    dest: "{{ nvim_share_dir }}/{{ nvim_packer_reldir }}"
    depth: 1

- name: Neovim | Find XDG Config Directories | file
  find:
    paths: "{{ xdg_config_dir }}"
    file_type: "directory"
  register: xdg_config_dirs

- name: Neovim | Symlink XDG Config Directories | file
  file:
    src: "{{ item.path }}"
    path: "{{ nvim_xdg_profile_dir['config'] }}/{{ nvim_profile_name }}/{{ item.path | basename }}"
    state: link
  with_items: "{{ xdg_config_dirs.files }}"

- name: Neovim | Remove Recursive Symlink | file
  file:
    path: "{{ nvim_xdg_profile_dir['config'] }}/{{ nvim_profile_name }}/{{ nvim_profile_dir_name }}"
    state: absent
