---
- name: tcsh | Copies .tcshrc | template
  template:
    src: tcsh/tcshrc.j2
    dest: "{{ tcsh_config_file }}"

- name: tcsh | Setup tcsh Config Directory | file
  file:
    path: "{{ tcsh_config_dir }}"
    state: directory
    mode: '0755'

- name: tcsh | Copy Tcsh Config Files | template
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ tcsh_config_dir }}/{{ item.path | regex_replace('\\.j2$', '') }}"
  with_community.general.filetree: "../templates/tcsh/config"
  when: item.state == 'file'
