---
- name: Neovim | Setup Neovim Config Directory | file
  file:
    path: "{{ nvim_config_dir }}"
    state: directory
    mode: '0755'

- name: Neovim | Setup Neovim Share(Data) Directory | file
  file:
    path: "{{ nvim_share_dir }}"
    state: directory
    mode: '0755'

- name: Neovim | Setup Neovim Cache Directory | file
  file:
    path: "{{ nvim_cache_dir }}"
    state: directory
    mode: '0755'

- name: Neovim | Copies Neovim Lua Config | template
  template:
    src: nvim-{{ nvim_profile_name }}/init.lua.j2
    dest: "{{ nvim_config_dir }}/init.lua"

- name: Neovim | Create Neovim Plugin Config Directories | file
  ansible.builtin.file:
    path: "{{ nvim_config_dir }}/{{ item.path }}"
    state: directory
  with_community.general.filetree: "../templates/nvim-{{ nvim_profile_name }}"
  when: item.state == 'directory'

- name: Neovim | Copy Neovim Plugin Config Files | template
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ nvim_config_dir }}/{{ item.path | regex_replace('\\.j2$', '') }}"
  with_community.general.filetree: "../templates/nvim-{{ nvim_profile_name }}"
  when: item.state == 'file'

- name: Neovim | Download Packer | git
  git:
    repo: "https://github.com/wbthomason/packer.nvim"
    dest: "{{ nvim_share_dir }}/{{ nvim_packer_reldir }}"
    depth: 1
