---
- name: Neovim | Setup Neovim Profile Directories | file
  file:
    path: "{{ item.value }}"
    state: directory
    mode: '0755'
  loop: "{{ nvim_xdg_profile_dir | dict2items }}"

- name: Neovim | Setup Neovim Profiles | file
  file:
    path: "{{ item.key }}/{{ item.value.name }}"
    state: directory
    mode: '0755'
  loop: "{{ nvim_xdg_profiles | dict2items }}"

- name: Neovim | Install Neovim Profile Configs | file
  vars:
    nvim_profile_name: "{{ item.value.name }}"
    nvim_config_dir: "{{ nvim_xdg_profile_dir['config'] }}/{{ item.value.name }}"
    nvim_share_dir: "{{ nvim_xdg_profile_dir['share'] }}/{{ item.value.name }}"
    nvim_cache_dir: "{{ nvim_xdg_profile_dir['cache'] }}/{{ item.value.name }}"
  import_tasks: tasks/install_neovim_profiles.yml
  loop: "{{ nvim_xdg_profiles | dict2items }}"
