---
- name: Direnv | Install Direnv | shell
  shell: "curl -sfL https://direnv.net/install.sh | bash"
  args:
    executable: /bin/bash
    creates: "{{ direnv_exe }}"

- name: Direnv | Copies Direnv Config | template
  template:
    src: "direnv/direnvrc.j2"
    dest: "{{ direnv_config }}"
