---
- name: Neovim | Setup Neovim Config Directory | file
  file:
    path: "{{ nvim_config_dir }}"
    state: directory
    mode: '0755'

- name: Neovim | Setup Neovim Share(Data) Directory | file
  file:
    path: "{{ nvim_share_dir }}"
    state: directory
    mode: '0755'

- name: Neovim | Setup Neovim Cache Directory | file
  file:
    path: "{{ nvim_cache_dir }}"
    state: directory
    mode: '0755'

- name: Neovim | Copies Neovim Lua Config | template
  template:
    src: nvim-cosynvim/init.lua.j2
    dest: "{{ nvim_init_lua }}"

- name: Setup Neovim Lua Config Directory
  file:
    path: "{{ nvim_lua_config_dir }}"
    state: directory
    mode: '0755'

- name: Neovim | Create Neovim Plugin Config Directories | file
  ansible.builtin.file:
    path: "{{ nvim_lua_config_dir }}/{{ item.path }}"
    state: directory
  with_community.general.filetree: "../templates/nvim-cosynvim/lua"
  when: item.state == 'directory'

- name: Neovim | Copy Neovim Plugin Config Files | template
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ nvim_lua_config_dir }}/{{ item.path | regex_replace('\\.j2$', '') }}"
  with_community.general.filetree: "../templates/nvim-cosynvim/lua"
  when: item.state == 'file'

