---
- name: Vars | Set Rust Baremetal Variables | set_fact
  ansible.builtin.set_fact:
    cargo_path: "{{ cargo_home }}/bin/"
    rust_analyzer_exe: "{{ rustup_path }}rust-analyzer"
    clippy_exe: "{{ rustup_path }}cargo-clippy"

- name: Vars | Set Tool Exe Variables | set_fact
  ansible.builtin.set_fact:
    zsh_devbox_env: ""
    atuin_exe: "{{ cargo_path }}atuin"
    astgrep_exe: "{{ cargo_path }}sg"
    bat_exe: "{{ cargo_path }}bat"
    broot_exe: "{{ cargo_path }}broot"
    bottom_exe: "{{ cargo_path }}btm"
    choose_exe: "{{ cargo_path }}choose"
    counts_exe: "{{ cargo_path }}counts"
    delta_exe: "{{ cargo_path }}delta"
    difftastic_exe: "{{ cargo_path }}difft"
    diffr_exe: "{{ cargo_path }}diffr"
    dust_exe: "{{ cargo_path }}dust"
    eva_exe: "{{ cargo_path }}eva"
    erdtree_exe: "{{ cargo_path }}et"
    exa_exe: "{{ cargo_path }}exz"
    fd_exe: "{{ cargo_path }}fd"
    felix_exe: "{{ cargo_path }}fx"
    fend_exe: "{{ cargo_path }}fend"
    grex_exe: "{{ cargo_path }}grex"
    gitui_exe: "{{ cargo_path }}gitui"
    hyperfine_exe: "{{ cargo_path }}hyperfine"
    joshuto_exe: "{{ cargo_path }}joshuto"
    just_exe: "{{ cargo_path }}just"
    lsd_exe: "{{ cargo_path }}lsd"
    macchina_exe: "{{ cargo_path }}macchina"
    mprocs_exe: "{{ cargo_path }}mprocs"
    navi_exe: "{{ cargo_path }}navi"
    nu_exe: "{{ cargo_path }}nu"
    ouch_exe: "{{ cargo_path }}ouch"
    procs_exe: "{{ cargo_path }}procs"
    rg_exe: "{{ cargo_path }}rg"
    rnr_exe: "{{ cargo_path }}rnr"
    sd_exe: "{{ cargo_path }}sd"
    skim_exe: "{{ cargo_path }}sk"
    starship_exe: "{{ cargo_path }}starship"
    wikitui_exe: "{{ cargo_path }}wiki-tui"
    xcp_exe: "{{ cargo_path }}xcp"
    xplr_exe: "{{ cargo_path }}xplr"
    yazi_exe: "{{ cargo_path }}yazi"
    zellij_exe: "{{ cargo_path }}zellij"
    zoxide_exe: "{{ cargo_path }}zoxide"
    fzf_exe: "{{ fzf_install_dir }}/bin/fzf"
    nvim_exe: "{{ nvim_exe_default }}"
