---
- name: XDG | Create XDG Directories | file
  file:
    path: "{{ item.value }}"
    state: directory
  loop: "{{ xdg_config_dirs | dict2items }}"

- name: XDG | Create XDG Directories | file
  file:
    path: "{{ dot_download_dir }}"
    state: directory
