---
nvim_intellisense_default:
  packer: |
    use { 'saadparwaiz1/cmp_luasnip',
      requires = {
        'numToStr/Comment.nvim',
        'neovim/nvim-lspconfig',
        'glepnir/lspsaga.nvim',
        'dnlhc/glance.nvim',
        'onsails/lspkind.nvim',
        'L3MON4D3/LuaSnip',
        'hrsh7th/nvim-cmp',
        'hrsh7th/cmp-buffer',
        'hrsh7th/cmp-path',
        'hrsh7th/cmp-nvim-lsp',
      },
    }
    use { 'stevearc/aerial.nvim', }
  lazy: |
    {
      "L3MON4D3/LuaSnip",
      version = "v2.0.0",
      -- build = "make install_jsregexp"
    },
    { 'saadparwaiz1/cmp_luasnip',
      dependencies = {
        'neovim/nvim-lspconfig',
        'glepnir/lspsaga.nvim',
        'hrsh7th/nvim-cmp',
        'hrsh7th/cmp-buffer',
        'hrsh7th/cmp-path',
        'hrsh7th/cmp-nvim-lsp',
      },
    },
    { 'mhartington/formatter.nvim' },
    { 'stevearc/aerial.nvim' },
    { 'dnlhc/glance.nvim' },
    { 'numToStr/Comment.nvim' },
    {
      'SmiteshP/nvim-navbuddy',
      dependencies = {
        'neovim/nvim-lspconfig',
        'SmiteshP/nvim-navic',
        'MunifTanjim/nui.nvim'
      }
    },
  config: |
    local navbuddy = require('nvim-navbuddy')
    -- Config(Lspconfig)
    local lspconfig = require('lspconfig')
    local on_attach = function(client, bufnr)
      navbuddy.attach(client, bufnr)
      vim.cmd [[ command! Format execute 'lua vim.lsp.buf.formatting()' ]]
    end
    -- local capabilities = vim.lsp.protocol.make_client_capabilities()
    local capabilities = require('cmp_nvim_lsp').default_capabilities()
    local servers = {
      'ansiblels',
      'bashls',
      {{ lsp_providers_luafile | indent(2) or '-- No Additional Servers Preconfigured' }}
    }
    for _, lsp in ipairs(servers) do
      lspconfig[lsp].setup {
        on_attach = on_attach,
        capabilities = capabilities,
      }
    end

    -- Config(Completion)
    local cmp = require('cmp')
    cmp.setup({
      snippet = {
        expand = function(args)
          require('luasnip').lsp_expand(args.body) -- For `luasnip` users.
        end,
      },
      window = {
        completion = cmp.config.window.bordered(),
        documentation = cmp.config.window.bordered(),
      },
      mapping = cmp.mapping.preset.insert({
        ['<C-b>'] = cmp.mapping.scroll_docs(-4),
        ['<C-f>'] = cmp.mapping.scroll_docs(4),
        ['<C-Space>'] = cmp.mapping.complete(),
        ['<C-e>'] = cmp.mapping.abort(),
        ['<CR>'] = cmp.mapping.confirm({ select = true }), -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
      }),
      sources = cmp.config.sources({
        { name = 'nvim_lsp' },
        { name = 'luasnip' }, -- For luasnip users.
      }, {
        { name = 'buffer' },
        { name = 'path' },
      }),
      {{ nvim_completion_config_cpp | indent(2) or '-- No Extra Completion Config' }}
    })

    -- Config(Lspsaga)
    require('lspsaga').setup({
      -- finder = {
      --   edit = { 'o', '<CR>' },
      --   vsplit = 'v',
      --   split = 'x',
      --   tabe = 't',
      --   quit = { 'q', '<ESC>' },
      -- },
      finder = {
        max_height = 0.5,
        min_width = 30,
        force_max_height = false,
        keys = {
          jump_to = 'p',
          expand_or_jump = 'o',
          vsplit = 's',
          split = 'i',
          tabe = 't',
          tabnew = 'r',
          quit = { 'q', '<ESC>' },
          close_in_preview = '<ESC>',
        },
      },
      definition = {
        edit = { 'o', '<CR>' },
        vsplit = 'v',
        split = 'x',
        tabe = 't',
        quit = { 'q', '<ESC>' },
      },
      symbol_in_winbar = {
        enable = true,
        separator = ' ',
        hide_keyword = true,
        show_file = true,
        folder_level = 2,
      },
    })
    vim.wo.winbar = require('lspsaga.symbol.winbar').get_bar()

    -- Config(Formatter)
    require('formatter').setup()

    -- Config(Misc)
    require('Comment').setup()
    require('aerial').setup({
      -- optionally use on_attach to set keymaps when aerial has attached to a buffer
      on_attach = function(bufnr)
        -- Jump forwards/backwards with '{' and '}'
        vim.keymap.set('n', '{', '<cmd>AerialPrev<CR>', {buffer = bufnr})
        vim.keymap.set('n', '}', '<cmd>AerialNext<CR>', {buffer = bufnr})
      end
    })
    require('glance').setup()
  keymaps: |
    -- { 'gd', { n = '<cmd>Lspsaga peek_definition<CR>', }, description = 'LSPSaga: Peek Definition', },
    -- { 'gd', { n = '<cmd>Lspsaga lsp_finder<CR>', }, description = 'LSPSaga: Definition/Reference Finder', },
    -- { 'ga', { n = '<cmd>Lspsaga code_action<CR>', }, description = 'LSPSaga: Definition/Reference Finder', },
    { 'gd', { n = '<cmd>Telescope lsp_definitions<CR>', }, description = 'Telescope: Definition Finder', },
    { 'gr', { n = '<cmd>Telescope lsp_references<CR>', }, description = 'Telescope: Reference Finder', },
    { 'gs', { n = '<cmd>Telescope lsp_document_symbols<CR>', }, description = 'Telescope: Document Symbol Finder', },
    { 'gS', { n = '<cmd>Telescope lsp_dynamic_workspace_symbols<CR>', }, description = 'Telescope: Workspace Symbol Finder', },
    -- { '<leader>ca', { n = '<cmd>Lspsaga code_action<CR>', }, description = 'LSPSaga: Code Action', },
    -- { '<leader>S', { n = '<cmd>Lspsaga outline<CR>', }, description = 'LSPSaga: Outline Toggle', },
    { '<leader>S', { n = '<cmd>AerialToggle! right<CR>', }, description = 'Aerial: Outline Toggle', },
    { 'K', { n = '<cmd>Lspsaga hover_doc<CR>', }, description = 'LSPSaga: Hover Docs', },
    { '[e', { n = '<cmd>Lspsaga diagnostic_jump_prev<CR>', }, description = 'LSPSaga: Previous Diagnostic', },
    { 'e]', { n = '<cmd>Lspsaga diagnostic_jump_next<CR>', }, description = 'LSPSaga: Next Diagnostic', },
    { '[E', { n = 'function() require(\'lspsaga.diagnostic\').goto_prev({ severity = vim.diagnostic.severity.ERROR }) end', }, description = 'LSPSaga: Previous Error', },
    { 'E]', { n = 'function() require(\'lspsaga.diagnostic\').goto_next({ severity = vim.diagnostic.severity.ERROR }) end', }, description = 'LSPSaga: Next Error', },
    { '<C-Space>', { n = '<cmd>lua require("nvim-navbuddy").open()<CR>', }, description = 'NavBuddy: Open', },
